### ISSUE TITLE
вопрос?

### ISSUE THREAD

**Issue by wa1985** [donOleg/Joomword#1]
Олег добрый день. Подскажите пожлст, вы имеете какое то отношение к сайту  https://joomword.com/index.php/ru/?

**Comment by donOleg** [comment]
Здравствуйте, а кто спрашивает?
Прямого отношения не имею.

29.08.2016, 19:58, "wa1985" <notifications@github.com>:

**Comment by wa1985** [comment]
Да у меня тестовое задание от этих ребят, интересно надежные ли они) Как они, заплатили за работу?

**Comment by donOleg** [comment]
Ясно, у меня тоже было тестовое задание.
Я его сделал и меня взяли на испытательный срок, но мне пришлось отказаться так как мне на то время предложили другую работу, на лучших условиях.
Так что можно сказать, что я с ними не работал, не могу подсказать как они платят и надежны ли, но как мне показалось за маленький срок, что они достаточно серьезны.

29.08.2016, 22:32, "wa1985" <notifications@github.com>:

**Comment by wa1985** [comment]
хорошо, я понял. спасибо за инфу!

**Comment by wa1985** [comment]
А если не секрет на какую сумму?

**Comment by donOleg** [comment]
Фиксированная сумма не обсуждалась, за месяц можно иметь разный доход, все зависит от объемов выполненных работ.
